// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aminpaks/go-streams/pkg/merrors (interfaces: Errorable)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockErrorable is a mock of Errorable interface.
type MockErrorable struct {
	ctrl     *gomock.Controller
	recorder *MockErrorableMockRecorder
}

// MockErrorableMockRecorder is the mock recorder for MockErrorable.
type MockErrorableMockRecorder struct {
	mock *MockErrorable
}

// NewMockErrorable creates a new mock instance.
func NewMockErrorable(ctrl *gomock.Controller) *MockErrorable {
	mock := &MockErrorable{ctrl: ctrl}
	mock.recorder = &MockErrorableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockErrorable) EXPECT() *MockErrorableMockRecorder {
	return m.recorder
}

// ErrorDetail mocks base method.
func (m *MockErrorable) ErrorDetail() interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ErrorDetail")
	ret0, _ := ret[0].(interface{})
	return ret0
}

// ErrorDetail indicates an expected call of ErrorDetail.
func (mr *MockErrorableMockRecorder) ErrorDetail() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorDetail", reflect.TypeOf((*MockErrorable)(nil).ErrorDetail))
}
